[features]
seeds = false
skip-lint = false
[programs.devnet]
fund_me = "9RWYAiFs9crPQiUu9tHrahZmpkbuAycgJ2LZ1zKoeZ3E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mrcleveer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
